### ISSUE TITLE
Poppler won't update

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/poppler-os2#1] opened 2020-03-23 14:44 UTC
Doing a Yum update here is failing. Seems like a typo as shown here,
```
Error: Package: poppler-utils-0.84.0-1.oc00.pentium4 (netlabs-exp)
           Requires: popple94.dll
           Available: poppler-0.84.0-1.oc00.i686 (netlabs-exp)
```
I think it should require popple84.dll

**Comment by SilvanScherrer** [comment] 2020-03-23 14:53
I wonder how you managed to not update poppler, as I did that several times. And no it's no type. the dll is popple94.dll
please show me the whole yum command and the whole output. As only this part says not really much.

**Comment by dryeo** [comment] 2020-03-23 14:59
I've only been updating certain packages. Power died right after posting
the issue so log will be later.

**Comment by dryeo** [comment] 2020-03-24 03:27
After doing a yum clean all, all I'm getting is 404 errors from 
Netlabs-rel and Netlabs-exp
```
http://rpm.netlabs.org/experimental/%24releasever/i386/repodata/repomd.xml: 
[Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: 
netlabs-exp. Please verify its path and try again
```

**Comment by SilvanScherrer** [comment] 2020-03-24 06:31
You seem to have hit the failing os2-release rpm. Latest is ok again. You need to download the rpm manually and install it. Then it runs again.

**Comment by dryeo** [comment] 2020-03-24 14:41
OK, that worked, thanks.
This issue can be closed

**Comment by SilvanScherrer** [comment] 2020-03-24 14:46
now you can update os2-release again to latest. as this works. does it also mean poppler could be updated?

**Comment by dryeo** [comment] 2020-03-24 15:06
Everything now seems to be up to date, at least with rel.
Hmm, ANPM seemed to have updated poppler but it must have quietly 
failed. Trying again from a local repository and command line results in 
this, I have to leave for work soon so will have to revisit tonight.
```
Setting up Update Process
Resolving Dependencies
--> Running transaction check
---> Package poppler.i686 0:0.61.1-1.oc00 will be updated
--> Processing Dependency: popple72.dll for package: 
poppler-utils-0.61.1-1.oc00.i686
--> Processing Dependency: poppler = 0.61.1-1.oc00 for package: 
poppler-utils-0.61.1-1.oc00.i686
---> Package poppler.pentium4 0:0.84.0-1.oc00 will be an update
---> Package poppler-cpp.i686 0:0.61.1-1.oc00 will be updated
---> Package poppler-cpp.pentium4 0:0.84.0-1.oc00 will be an update
--> Finished Dependency Resolution
Error: Package: poppler-utils-0.61.1-1.oc00.i686 (installed)
            Requires: popple72.dll
            Removing: poppler-0.61.1-1.oc00.i686 (installed)
                popple72.dll
            Updated By: poppler-0.84.0-1.oc00.pentium4 (local)
                Not found
Error: Package: poppler-utils-0.61.1-1.oc00.i686 (installed)
            Requires: poppler = 0.61.1-1.oc00
            Removing: poppler-0.61.1-1.oc00.i686 (installed)
                poppler = 0.61.1-1.oc00
            Updated By: poppler-0.84.0-1.oc00.pentium4 (local)
                poppler = 0.84.0-1.oc00
            Installed: poppler-legacy-66-0.52.0-1.oc00.L.i686 (installed)
                poppler = 0.52.0-1.oc00.L
            Installed: poppler-legacy-70-0.59.0-3.oc00.L.i686 (installed)
                poppler = 0.59.0-3.oc00.L
            Available: poppler-0.26.5-1.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-1.oc00
            Available: poppler-0.26.5-2.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-2.oc00
            Available: poppler-0.26.5-3.oc00.i686 (local)
                poppler = 0.26.5-3.oc00
            Available: poppler-0.29.0-0.oc00.i686 (local)
                poppler = 0.29.0-0.oc00
            Available: poppler-0.31.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.31.0-1.oc00
            Available: poppler-0.33.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.33.0-1.oc00
            Available: poppler-0.35.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.35.0-1.oc00
            Available: poppler-0.38.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.38.0-1.oc00
            Available: poppler-0.38.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.38.0-2.oc00
            Available: poppler-0.38.0-3.oc00.i686 (local)
                poppler = 0.38.0-3.oc00
            Available: poppler-0.42.0-2.oc00.i686 (local)
                poppler = 0.42.0-2.oc00
            Available: poppler-0.47.0-1.oc00.i686 (local)
                poppler = 0.47.0-1.oc00
            Available: poppler-0.49.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.49.0-1.oc00
            Available: poppler-0.49.0-2.oc00.i686 (local)
                poppler = 0.49.0-2.oc00
            Available: poppler-0.52.0-1.oc00.i686 (local)
                poppler = 0.52.0-1.oc00
            Available: poppler-0.59.0-1.oc00.i686 (local)
                poppler = 0.59.0-1.oc00
            Available: poppler-0.59.0-2.oc00.i686 (local)
                poppler = 0.59.0-2.oc00
            Available: poppler-0.59.0-3.oc00.i686 (local)
                poppler = 0.59.0-3.oc00
            Available: poppler-legacy-63-0.47.0-1.oc00.L.i686 (local)
                poppler = 0.47.0-1.oc00.L
            Available: poppler-legacy-65-0.49.0-2.oc00.L.i686 (local)
                poppler = 0.49.0-2.oc00.L
  You could try using --skip-broken to work around the problem
** Found 3 pre-existing rpmdb problem(s), 'yum check' output follows:
cups-filters-1.17.2-3.oc00.i686 has missing requires of 
cups-filters-libs = ('0', '1.17.2', '3.oc00')
cups-filters-1.17.2-3.oc00.i686 has missing requires of qpdf17.dll
cups-filters-1.25.6-1.oc00.i686 is a duplicate with 
cups-filters-1.17.2-3.oc00.i686
```

**Comment by SilvanScherrer** [comment] 2020-03-24 17:31
Your local repo is not complete. Please use rel and exp only. If you think its complete Show me yum list poppler*

**Comment by dryeo** [comment] 2020-03-25 03:26
I've downloaded all the Pentium4 poppler files in exp and added them to my local repository,
```
Installed Packages
poppler.i686                           0.61.1-1.oc00                installed   
poppler-cpp.i686                       0.61.1-1.oc00                @netlabs-exp
poppler-data.noarch                    0.4.9-1.oc00                 installed   
poppler-legacy-66.i686                 0.52.0-1.oc00.L              installed   
poppler-legacy-70.i686                 0.59.0-3.oc00.L              installed   
poppler-utils.i686                     0.61.1-1.oc00                installed   
Available Packages
poppler.i386                           0.38.0-1.oc00                netlabs-rel 
poppler.pentium4                       0.84.0-1.oc00                local       
poppler-cpp.i386                       0.38.0-1.oc00                netlabs-rel 
poppler-cpp.pentium4                   0.84.0-1.oc00                local       
poppler-cpp-devel.i386                 0.38.0-1.oc00                netlabs-rel 
poppler-cpp-devel.i686                 0.61.1-1.oc00                netlabs-rel 
poppler-cpp-devel.pentium4             0.84.0-1.oc00                local       
poppler-data-devel.noarch              0.4.9-1.oc00                 netlabs-rel 
poppler-debug.i386                     0.38.0-1.oc00                netlabs-rel 
poppler-debug.i686                     0.38.0-3.oc00                netlabs-rel 
poppler-debug.pentium4                 0.38.0-3.oc00                netlabs-rel 
poppler-debuginfo.i686                 0.61.1-1.oc00                netlabs-rel 
poppler-debuginfo.pentium4             0.84.0-1.oc00                local       
poppler-devel.i386                     0.38.0-1.oc00                netlabs-rel 
poppler-devel.i686                     0.61.1-1.oc00                netlabs-rel 
poppler-devel.pentium4                 0.84.0-1.oc00                local       
poppler-legacy-63.i686                 0.47.0-1.oc00.L              local       
poppler-legacy-63.pentium4             0.47.0-1.oc00.L              netlabs-rel 
poppler-legacy-65.i686                 0.49.0-2.oc00.L              local       
poppler-legacy-65.pentium4             0.49.0-2.oc00.L              local       
poppler-legacy-66.pentium4             0.52.0-1.oc00.L              local       
poppler-legacy-70.pentium4             0.59.0-3.oc00.L              local       
poppler-legacy-72.pentium4             0.61.1-1.oc00.L              local       
poppler-qt.i386                        0.38.0-1.oc00                netlabs-rel 
poppler-qt.i686                        0.61.1-1.oc00                netlabs-rel 
poppler-qt.pentium4                    0.84.0-1.oc00                local       
poppler-qt-devel.i386                  0.38.0-1.oc00                netlabs-rel 
poppler-qt-devel.i686                  0.61.1-1.oc00                netlabs-rel 
poppler-qt-devel.pentium4              0.84.0-1.oc00                local       
poppler-qt5.i686                       0.61.1-1.oc00                netlabs-rel 
poppler-qt5.pentium4                   0.84.0-1.oc00                local       
poppler-qt5-devel.i686                 0.61.1-1.oc00                netlabs-rel 
poppler-qt5-devel.pentium4             0.84.0-1.oc00                local       
poppler-utils.i386                     0.38.0-1.oc00                netlabs-rel 
poppler-utils.pentium4                 0.84.0-1.oc00                local       
```

**Comment by SilvanScherrer** [comment] 2020-03-25 09:52
Why do you use the local repo and not exp?
As i still dont see why it should not run. Especially it did here and for several tested.
Please attach thr complete yum log. Dont use anpm is i want the pur yum output and the yum command you use.

**Comment by dryeo** [comment] 2020-03-25 15:28
I was getting 404 errors with exp. Seems OK today so disabled local.
Output of "yum update" is,
```
Setting up Update Process
Resolving Dependencies
--> Running transaction check
---> Package libmpc.i686 0:1.1.0-1.oc00 will be obsoleting
--> Processing Dependency: mpfr6.dll for package: libmpc-1.1.0-1.oc00.i686
---> Package libmpc3.i686 0:1.0.1-3 will be obsoleted
---> Package poppler.i686 0:0.61.1-1.oc00 will be obsoleted
---> Package poppler-cpp.i686 0:0.61.1-1.oc00 will be updated
---> Package poppler-cpp.pentium4 0:0.84.0-1.oc00 will be an update
--> Processing Dependency: poppler = 0.84.0-1.oc00 for package: 
poppler-cpp-0.84.0-1.oc00.pentium4
--> Processing Dependency: popple94.dll for package: 
poppler-cpp-0.84.0-1.oc00.pentium4
---> Package poppler-legacy-72.i686 0:0.61.1-1.oc00.L will be obsoleting
---> Package poppler-utils.i686 0:0.61.1-1.oc00 will be updated
---> Package poppler-utils.pentium4 0:0.84.0-1.oc00 will be an update
--> Processing Dependency: poppler = 0.84.0-1.oc00 for package: 
poppler-utils-0.84.0-1.oc00.pentium4
--> Processing Dependency: popple94.dll for package: 
poppler-utils-0.84.0-1.oc00.pentium4
--> Running transaction check
---> Package mpfr.pentium4 0:4.0.2-1.oc00 will be installed
---> Package poppler-cpp.pentium4 0:0.84.0-1.oc00 will be an update
--> Processing Dependency: poppler = 0.84.0-1.oc00 for package: 
poppler-cpp-0.84.0-1.oc00.pentium4
--> Processing Dependency: popple94.dll for package: 
poppler-cpp-0.84.0-1.oc00.pentium4
---> Package poppler-utils.pentium4 0:0.84.0-1.oc00 will be an update
--> Processing Dependency: poppler = 0.84.0-1.oc00 for package: 
poppler-utils-0.84.0-1.oc00.pentium4
--> Processing Dependency: popple94.dll for package: 
poppler-utils-0.84.0-1.oc00.pentium4
--> Finished Dependency Resolution
Error: Package: poppler-cpp-0.84.0-1.oc00.pentium4 (netlabs-exp)
            Requires: poppler = 0.84.0-1.oc00
            Removing: poppler-0.61.1-1.oc00.i686 (installed)
                poppler = 0.61.1-1.oc00
            Obsoleted By: poppler-legacy-72-0.61.1-1.oc00.L.i686 
(netlabs-exp)
                poppler = 0.61.1-1.oc00.L
            Installed: poppler-legacy-66-0.52.0-1.oc00.L.i686 (installed)
                poppler = 0.52.0-1.oc00.L
            Installed: poppler-legacy-70-0.59.0-3.oc00.L.i686 (installed)
                poppler = 0.59.0-3.oc00.L
            Available: poppler-0.26.5-1.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-1.oc00
            Available: poppler-0.26.5-2.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-2.oc00
            Available: poppler-0.26.5-3.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-3.oc00
            Available: poppler-0.29.0-0.oc00.i686 (netlabs-rel)
                poppler = 0.29.0-0.oc00
            Available: poppler-0.31.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.31.0-1.oc00
            Available: poppler-0.33.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.33.0-1.oc00
            Available: poppler-0.35.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.35.0-1.oc00
            Available: poppler-0.38.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.38.0-1.oc00
            Available: poppler-0.38.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.38.0-2.oc00
            Available: poppler-0.38.0-3.oc00.i686 (netlabs-rel)
                poppler = 0.38.0-3.oc00
            Available: poppler-0.42.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.42.0-2.oc00
            Available: poppler-0.47.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.47.0-1.oc00
            Available: poppler-0.49.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.49.0-1.oc00
            Available: poppler-0.49.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.49.0-2.oc00
            Available: poppler-0.52.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.52.0-1.oc00
            Available: poppler-0.59.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.59.0-2.oc00
            Available: poppler-0.59.0-3.oc00.i686 (netlabs-rel)
                poppler = 0.59.0-3.oc00
            Available: poppler-0.84.0-1.oc00.i686 (netlabs-exp)
                poppler = 0.84.0-1.oc00
            Available: poppler-legacy-63-0.47.0-1.oc00.L.i686 (netlabs-rel)
                poppler = 0.47.0-1.oc00.L
            Available: poppler-legacy-65-0.49.0-2.oc00.L.i686 (netlabs-exp)
                poppler = 0.49.0-2.oc00.L
Error: Package: poppler-utils-0.84.0-1.oc00.pentium4 (netlabs-exp)
            Requires: popple94.dll
            Available: poppler-0.84.0-1.oc00.i686 (netlabs-exp)
                popple94.dll
            Removing: poppler-0.61.1-1.oc00.i686 (installed)
                Not found
            Obsoleted By: poppler-legacy-72-0.61.1-1.oc00.L.i686 
(netlabs-exp)
                Not found
            Available: poppler-0.26.5-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.26.5-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.26.5-3.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.29.0-0.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.31.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.33.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.35.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.38.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.38.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.38.0-3.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.42.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.47.0-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.49.0-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.49.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.52.0-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.59.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.59.0-3.oc00.i686 (netlabs-rel)
                Not found
Error: Package: poppler-cpp-0.84.0-1.oc00.pentium4 (netlabs-exp)
            Requires: popple94.dll
            Available: poppler-0.84.0-1.oc00.i686 (netlabs-exp)
                popple94.dll
            Removing: poppler-0.61.1-1.oc00.i686 (installed)
                Not found
            Obsoleted By: poppler-legacy-72-0.61.1-1.oc00.L.i686 
(netlabs-exp)
                Not found
            Available: poppler-0.26.5-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.26.5-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.26.5-3.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.29.0-0.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.31.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.33.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.35.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.38.0-1.oc00.i386 (netlabs-rel)
                Not found
            Available: poppler-0.38.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.38.0-3.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.42.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.47.0-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.49.0-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.49.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.52.0-1.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.59.0-2.oc00.i686 (netlabs-rel)
                Not found
            Available: poppler-0.59.0-3.oc00.i686 (netlabs-rel)
                Not found
Error: Package: poppler-utils-0.84.0-1.oc00.pentium4 (netlabs-exp)
            Requires: poppler = 0.84.0-1.oc00
            Removing: poppler-0.61.1-1.oc00.i686 (installed)
                poppler = 0.61.1-1.oc00
            Obsoleted By: poppler-legacy-72-0.61.1-1.oc00.L.i686 
(netlabs-exp)
                poppler = 0.61.1-1.oc00.L
            Installed: poppler-legacy-66-0.52.0-1.oc00.L.i686 (installed)
                poppler = 0.52.0-1.oc00.L
            Installed: poppler-legacy-70-0.59.0-3.oc00.L.i686 (installed)
                poppler = 0.59.0-3.oc00.L
            Available: poppler-0.26.5-1.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-1.oc00
            Available: poppler-0.26.5-2.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-2.oc00
            Available: poppler-0.26.5-3.oc00.i686 (netlabs-rel)
                poppler = 0.26.5-3.oc00
            Available: poppler-0.29.0-0.oc00.i686 (netlabs-rel)
                poppler = 0.29.0-0.oc00
            Available: poppler-0.31.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.31.0-1.oc00
            Available: poppler-0.33.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.33.0-1.oc00
            Available: poppler-0.35.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.35.0-1.oc00
            Available: poppler-0.38.0-1.oc00.i386 (netlabs-rel)
                poppler = 0.38.0-1.oc00
            Available: poppler-0.38.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.38.0-2.oc00
            Available: poppler-0.38.0-3.oc00.i686 (netlabs-rel)
                poppler = 0.38.0-3.oc00
            Available: poppler-0.42.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.42.0-2.oc00
            Available: poppler-0.47.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.47.0-1.oc00
            Available: poppler-0.49.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.49.0-1.oc00
            Available: poppler-0.49.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.49.0-2.oc00
            Available: poppler-0.52.0-1.oc00.i686 (netlabs-rel)
                poppler = 0.52.0-1.oc00
            Available: poppler-0.59.0-2.oc00.i686 (netlabs-rel)
                poppler = 0.59.0-2.oc00
            Available: poppler-0.59.0-3.oc00.i686 (netlabs-rel)
                poppler = 0.59.0-3.oc00
            Available: poppler-0.84.0-1.oc00.i686 (netlabs-exp)
                poppler = 0.84.0-1.oc00
            Available: poppler-legacy-63-0.47.0-1.oc00.L.i686 (netlabs-rel)
                poppler = 0.47.0-1.oc00.L
            Available: poppler-legacy-65-0.49.0-2.oc00.L.i686 (netlabs-exp)
                poppler = 0.49.0-2.oc00.L
  You could try using --skip-broken to work around the problem
** Found 3 pre-existing rpmdb problem(s), 'yum check' output follows:
cups-filters-1.17.2-3.oc00.i686 has missing requires of 
cups-filters-libs = ('0', '1.17.2', '3.oc00')
cups-filters-1.17.2-3.oc00.i686 has missing requires of qpdf17.dll
cups-filters-1.25.6-1.oc00.i686 is a duplicate with 
cups-filters-1.17.2-3.oc00.i686
```

**Comment by SilvanScherrer** [comment] 2020-03-25 16:20
do you switch between different archs? as I suspect a bigger issue on your side after the crashes you saw. As I can't reproduce that. try to use a clean env and retry

**Comment by SilvanScherrer** [comment] 2020-03-25 18:15
I might have an idea. But i need to check that first which takes a while as im busy with more important stuff

**Comment by dryeo** [comment] 2020-03-26 02:34
Changing to i686 fixed this issue. Still seems weird that RPM can't 
handle this correctly, even trying to use the replace plugin.
There's no reason, besides really old hardware, that i686 and Pentium 4 
code can't be mixed
Thanks and stay healthy.

**Comment by SilvanScherrer** [comment] 2020-03-26 09:19
Thx for the info. And its not that the code cant be mixed. Its deep in yum that it cant mix arch sometimes. Easy rpm work like a charm but complex requires snd such dont.  Why i never looked close enough.
As all works now i close the issue.

**Closed as completed by SilvanScherrer** 2020-03-26 09:19 UTC
